// Australian Residential Construction Rates 2024
// Based on Rawlinsons Australian Construction Handbook 2024 and current market data
// All rates in AUD, quantities in metric

export interface ConstructionRate {
  code: string;
  description: string;
  category: SOWCategory;
  subCategory: string;
  unit: 'm2' | 'm' | 'each' | 'item' | 'lm' | 'm3' | 'kg' | 'hr' | 'lot';
  materialRate: number;  // $ per unit
  labourRate: number;    // $ per hour
  labourHours: number;   // hours per unit
  totalRate: number;     // total $ per unit
  notes?: string;
}

// Schedule of Works Categories
export type SOWCategory =
  | 'PRELIMINARIES'
  | 'SITE_WORKS'
  | 'STRUCTURE'
  | 'FRAMING_TRUSS'
  | 'EXTERNAL'
  | 'ROOFING'
  | 'WINDOWS_DOORS'
  | 'INTERNAL_LININGS'
  | 'INTERNAL_FIT_OUT'
  | 'ELECTRICAL'
  | 'PLUMBING'
  | 'HVAC'
  | 'PAINTING'
  | 'FLOOR_COVERINGS'
  | 'EXTERNAL_WORKS'
  | 'CERTIFICATIONS';

export const SOW_CATEGORY_LABELS: Record<SOWCategory, string> = {
  PRELIMINARIES: 'Preliminaries',
  SITE_WORKS: 'Site Works',
  STRUCTURE: 'Structure (Slab & Foundations)',
  FRAMING_TRUSS: 'Framing & Truss',
  EXTERNAL: 'External Cladding & Masonry',
  ROOFING: 'Roofing',
  WINDOWS_DOORS: 'Windows & Doors',
  INTERNAL_LININGS: 'Internal Linings',
  INTERNAL_FIT_OUT: 'Internal Fit-out & Joinery',
  ELECTRICAL: 'Electrical',
  PLUMBING: 'Plumbing & Drainage',
  HVAC: 'HVAC / Mechanical',
  PAINTING: 'Painting',
  FLOOR_COVERINGS: 'Floor Coverings',
  EXTERNAL_WORKS: 'External Works & Landscaping',
  CERTIFICATIONS: 'Certifications & Compliance',
};

// Category display order
export const SOW_CATEGORY_ORDER: SOWCategory[] = [
  'PRELIMINARIES',
  'SITE_WORKS',
  'STRUCTURE',
  'FRAMING_TRUSS',
  'ROOFING',
  'EXTERNAL',
  'WINDOWS_DOORS',
  'INTERNAL_LININGS',
  'INTERNAL_FIT_OUT',
  'ELECTRICAL',
  'PLUMBING',
  'HVAC',
  'PAINTING',
  'FLOOR_COVERINGS',
  'EXTERNAL_WORKS',
  'CERTIFICATIONS',
];

// Construction rates — calibrated to 2024 Australian residential market
// Sources: Rawlinsons 2024, Master Builders Queensland/NSW, ABS Building Activity data
export const AUSTRALIAN_CONSTRUCTION_RATES: ConstructionRate[] = [

  // === PRELIMINARIES ===
  // PRELIM-01/02 unit is m2 — quantity in code = totalFloorArea, so rate reflects $/m² of GFA
  {
    code: 'PRELIM-01',
    description: 'Site establishment, supervision & temporary facilities',
    category: 'PRELIMINARIES',
    subCategory: 'Setup',
    unit: 'm2',
    materialRate: 0,
    labourRate: 95,
    labourHours: 0.5,
    totalRate: 47.50,
    notes: 'Covers site manager, temp power/water, safety signage, waste skips — scaled per m² GFA',
  },
  {
    code: 'PRELIM-02',
    description: 'Site office, amenities, temporary fencing & hoarding',
    category: 'PRELIMINARIES',
    subCategory: 'Setup',
    unit: 'm2',
    materialRate: 0,
    labourRate: 85,
    labourHours: 0.25,
    totalRate: 21.25,
    notes: 'Site shed, toilet, perimeter fence — scaled per m² GFA',
  },
  {
    code: 'PRELIM-03',
    description: 'Temporary fencing (linear metre)',
    category: 'PRELIMINARIES',
    subCategory: 'Protection',
    unit: 'lm',
    materialRate: 55,
    labourRate: 60,
    labourHours: 0.15,
    totalRate: 64.00,
  },

  // === SITE WORKS ===
  {
    code: 'SITE-01',
    description: 'Site clearing and stripping (topsoil, vegetation)',
    category: 'SITE_WORKS',
    subCategory: 'Earthworks',
    unit: 'm2',
    materialRate: 0,
    labourRate: 90,
    labourHours: 0.025,
    totalRate: 2.25,
  },
  {
    code: 'SITE-02',
    description: 'Cut and fill earthworks (average)',
    category: 'SITE_WORKS',
    subCategory: 'Earthworks',
    unit: 'm3',
    materialRate: 0,
    labourRate: 100,
    labourHours: 0.3,
    totalRate: 30.00,
  },
  {
    code: 'SITE-03',
    description: 'Compacted fill to building pad',
    category: 'SITE_WORKS',
    subCategory: 'Earthworks',
    unit: 'm3',
    materialRate: 42,
    labourRate: 90,
    labourHours: 0.18,
    totalRate: 58.20,
  },

  // === STRUCTURE ===
  {
    code: 'STRUCT-01',
    description: 'Waffle pod slab on ground (standard residential)',
    category: 'STRUCTURE',
    subCategory: 'Slab',
    unit: 'm2',
    materialRate: 135,
    labourRate: 90,
    labourHours: 0.43,
    totalRate: 173.70,
    notes: 'Includes mesh, vapour barrier, edge beams, concrete pump; class M–H site',
  },
  {
    code: 'STRUCT-02',
    description: 'Raft slab on ground (M–H class site)',
    category: 'STRUCTURE',
    subCategory: 'Slab',
    unit: 'm2',
    materialRate: 155,
    labourRate: 90,
    labourHours: 0.5,
    totalRate: 200.00,
  },
  {
    code: 'STRUCT-03',
    description: 'Strip footings',
    category: 'STRUCTURE',
    subCategory: 'Footings',
    unit: 'lm',
    materialRate: 80,
    labourRate: 90,
    labourHours: 0.55,
    totalRate: 129.50,
  },
  {
    code: 'STRUCT-04',
    description: 'Concrete driveway 100mm',
    category: 'STRUCTURE',
    subCategory: 'Concrete',
    unit: 'm2',
    materialRate: 55,
    labourRate: 80,
    labourHours: 0.28,
    totalRate: 77.40,
  },
  {
    code: 'STRUCT-05',
    description: 'First floor structure (timber cassette/floor joists, upper level)',
    category: 'STRUCTURE',
    subCategory: 'Upper Floor',
    unit: 'm2',
    materialRate: 120,
    labourRate: 90,
    labourHours: 0.55,
    totalRate: 169.50,
    notes: 'Per m² of upper floor area — includes LVL bearers, floor joists, noggings, flooring sheet',
  },

  // === FRAMING & TRUSS ===
  {
    code: 'FRAME-01',
    description: 'Timber wall framing (90x45 studs @ 450cc)',
    category: 'FRAMING_TRUSS',
    subCategory: 'Wall Framing',
    unit: 'm2',
    materialRate: 52,
    labourRate: 80,
    labourHours: 0.4,
    totalRate: 84.00,
  },
  {
    code: 'FRAME-02',
    description: 'Steel wall framing (light gauge)',
    category: 'FRAMING_TRUSS',
    subCategory: 'Wall Framing',
    unit: 'm2',
    materialRate: 68,
    labourRate: 90,
    labourHours: 0.42,
    totalRate: 105.80,
  },
  {
    code: 'FRAME-03',
    description: 'Roof trusses (standard residential, engineered)',
    category: 'FRAMING_TRUSS',
    subCategory: 'Roof Framing',
    unit: 'm2',
    materialRate: 65,
    labourRate: 80,
    labourHours: 0.34,
    totalRate: 92.20,
    notes: 'Price per m² of floor area covered; includes crane lift and fixing',
  },
  {
    code: 'FRAME-04',
    description: 'Ceiling joists/battens',
    category: 'FRAMING_TRUSS',
    subCategory: 'Ceiling Framing',
    unit: 'm2',
    materialRate: 22,
    labourRate: 70,
    labourHours: 0.17,
    totalRate: 33.90,
  },
  {
    code: 'FRAME-05',
    description: 'Floor framing (timber, upper level)',
    category: 'FRAMING_TRUSS',
    subCategory: 'Floor Framing',
    unit: 'm2',
    materialRate: 98,
    labourRate: 80,
    labourHours: 0.46,
    totalRate: 134.80,
  },

  // === ROOFING ===
  {
    code: 'ROOF-01',
    description: 'Colorbond roofing (Trimdek/Custom Orb, supply & fix)',
    category: 'ROOFING',
    subCategory: 'Roof Covering',
    unit: 'm2',
    materialRate: 65,
    labourRate: 88,
    labourHours: 0.37,
    totalRate: 97.56,
    notes: 'Includes flashings, screws, ridge capping; excludes fascia/gutters',
  },
  {
    code: 'ROOF-02',
    description: 'Concrete roof tiles (monier style)',
    category: 'ROOFING',
    subCategory: 'Roof Covering',
    unit: 'm2',
    materialRate: 82,
    labourRate: 82,
    labourHours: 0.46,
    totalRate: 119.72,
  },
  {
    code: 'ROOF-03',
    description: 'Sarking/building wrap (reflective foil)',
    category: 'ROOFING',
    subCategory: 'Roof Underlay',
    unit: 'm2',
    materialRate: 10,
    labourRate: 60,
    labourHours: 0.06,
    totalRate: 13.60,
  },
  {
    code: 'ROOF-04',
    description: 'Fascia and barge boards (Colorbond, supply & fix)',
    category: 'ROOFING',
    subCategory: 'Fascia/Gutters',
    unit: 'lm',
    materialRate: 38,
    labourRate: 72,
    labourHours: 0.28,
    totalRate: 58.16,
  },
  {
    code: 'ROOF-05',
    description: 'Gutters (Colorbond quad 125mm, supply & fix)',
    category: 'ROOFING',
    subCategory: 'Fascia/Gutters',
    unit: 'lm',
    materialRate: 28,
    labourRate: 70,
    labourHours: 0.23,
    totalRate: 44.10,
  },
  {
    code: 'ROOF-06',
    description: 'Downpipes (Colorbond 90mm rectangular, supply & fix)',
    category: 'ROOFING',
    subCategory: 'Fascia/Gutters',
    unit: 'lm',
    materialRate: 28,
    labourRate: 70,
    labourHours: 0.22,
    totalRate: 43.40,
  },

  // === EXTERNAL ===
  {
    code: 'EXT-01',
    description: 'Brick veneer (standard face brick, inc. ties, DPC, weeps)',
    category: 'EXTERNAL',
    subCategory: 'Masonry',
    unit: 'm2',
    materialRate: 105,
    labourRate: 92,
    labourHours: 0.95,
    totalRate: 192.40,
  },
  {
    code: 'EXT-02',
    description: 'Hebel PowerPanel 75mm (supply, fix, prime)',
    category: 'EXTERNAL',
    subCategory: 'Cladding',
    unit: 'm2',
    materialRate: 82,
    labourRate: 80,
    labourHours: 0.38,
    totalRate: 112.40,
  },
  {
    code: 'EXT-03',
    description: 'Weatherboard cladding (fibre cement, painted)',
    category: 'EXTERNAL',
    subCategory: 'Cladding',
    unit: 'm2',
    materialRate: 62,
    labourRate: 80,
    labourHours: 0.43,
    totalRate: 96.40,
  },
  {
    code: 'EXT-04',
    description: 'Acrylic render to FC sheeting (two-coat, inc. texture)',
    category: 'EXTERNAL',
    subCategory: 'Render',
    unit: 'm2',
    materialRate: 58,
    labourRate: 78,
    labourHours: 0.44,
    totalRate: 92.32,
    notes: 'Includes base coat, finish coat, corner beads; excludes painting',
  },
  {
    code: 'EXT-05',
    description: 'Feature weatherboard — James Hardie Linea / Weathertex',
    category: 'EXTERNAL',
    subCategory: 'Cladding',
    unit: 'm2',
    materialRate: 92,
    labourRate: 80,
    labourHours: 0.45,
    totalRate: 128.00,
  },
  {
    code: 'EXT-06',
    description: 'Aluminium feature battens (Knotwood or similar)',
    category: 'EXTERNAL',
    subCategory: 'Cladding',
    unit: 'm2',
    materialRate: 168,
    labourRate: 88,
    labourHours: 0.52,
    totalRate: 213.76,
  },
  {
    code: 'EXT-07',
    description: 'Besser block / breeze block feature wall (rendered or face)',
    category: 'EXTERNAL',
    subCategory: 'Masonry',
    unit: 'm2',
    materialRate: 100,
    labourRate: 90,
    labourHours: 1.1,
    totalRate: 199.00,
  },

  // === WINDOWS & DOORS ===
  {
    code: 'WD-01',
    description: 'Aluminium sliding window (standard, powder coated)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Windows',
    unit: 'each',
    materialRate: 540,
    labourRate: 82,
    labourHours: 1.7,
    totalRate: 679.40,
    notes: 'Average 1200×1200mm, Crimsafe-ready frame; install includes flashing',
  },
  {
    code: 'WD-02',
    description: 'Aluminium awning window (powder coated)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Windows',
    unit: 'each',
    materialRate: 460,
    labourRate: 82,
    labourHours: 1.5,
    totalRate: 583.00,
  },
  {
    code: 'WD-03',
    description: 'Large sliding door (2400mm wide, aluminium)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 1550,
    labourRate: 90,
    labourHours: 2.8,
    totalRate: 1802.00,
  },
  {
    code: 'WD-04',
    description: 'Internal door (hollow core, 820×2040) with frame & hardware',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 355,
    labourRate: 80,
    labourHours: 1.55,
    totalRate: 479.00,
  },
  {
    code: 'WD-05',
    description: 'Internal door (solid core) with frame & hardware',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 560,
    labourRate: 80,
    labourHours: 1.55,
    totalRate: 684.00,
  },
  {
    code: 'WD-06',
    description: 'External entry door (solid core, 920×2040) with frame & hardware',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 1100,
    labourRate: 90,
    labourHours: 2.8,
    totalRate: 1352.00,
  },
  {
    code: 'WD-07',
    description: 'Garage door (sectional panel lift) single',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 1800,
    labourRate: 90,
    labourHours: 4.2,
    totalRate: 2178.00,
    notes: 'Single 2700×2100mm; includes motor, remote, auto-reverse',
  },
  {
    code: 'WD-08',
    description: 'Garage door (sectional panel lift) double',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 2700,
    labourRate: 90,
    labourHours: 5.2,
    totalRate: 3168.00,
  },
  {
    code: 'WD-09',
    description: 'Sliding wardrobe doors (mirrored, per lm)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'lm',
    materialRate: 340,
    labourRate: 80,
    labourHours: 0.55,
    totalRate: 384.00,
  },
  {
    code: 'WD-10',
    description: 'Sliding stacker door (3-panel aluminium, ~3.6m opening)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 3400,
    labourRate: 90,
    labourHours: 3.8,
    totalRate: 3742.00,
  },
  {
    code: 'WD-11',
    description: 'Louvre window (aluminium, residential)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Windows',
    unit: 'each',
    materialRate: 520,
    labourRate: 80,
    labourHours: 1.6,
    totalRate: 648.00,
  },
  {
    code: 'WD-12',
    description: 'Curved / feature window (aluminium, custom)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Windows',
    unit: 'each',
    materialRate: 2800,
    labourRate: 90,
    labourHours: 3.2,
    totalRate: 3088.00,
  },

  // === INTERNAL LININGS ===
  {
    code: 'INT-01',
    description: 'Plasterboard walls (13mm standard, fix, set & stop)',
    category: 'INTERNAL_LININGS',
    subCategory: 'Walls',
    unit: 'm2',
    materialRate: 30,
    labourRate: 72,
    labourHours: 0.39,
    totalRate: 58.08,
    notes: 'Supply, fix, set and sand 3 coats; ready for paint',
  },
  {
    code: 'INT-02',
    description: 'Plasterboard ceiling (10mm, fix, set & stop)',
    category: 'INTERNAL_LININGS',
    subCategory: 'Ceilings',
    unit: 'm2',
    materialRate: 33,
    labourRate: 72,
    labourHours: 0.43,
    totalRate: 63.96,
  },
  {
    code: 'INT-03',
    description: 'Villaboard wet area lining (6mm, fix & set)',
    category: 'INTERNAL_LININGS',
    subCategory: 'Wet Areas',
    unit: 'm2',
    materialRate: 50,
    labourRate: 72,
    labourHours: 0.42,
    totalRate: 80.24,
  },
  {
    code: 'INT-04',
    description: 'Wet area waterproofing membrane (AS 3740)',
    category: 'INTERNAL_LININGS',
    subCategory: 'Wet Areas',
    unit: 'm2',
    materialRate: 38,
    labourRate: 72,
    labourHours: 0.42,
    totalRate: 68.24,
    notes: '2-coat liquid membrane; includes fillets, seams, corners',
  },
  {
    code: 'INT-05',
    description: 'Ceiling insulation R4.0 (glasswool batts)',
    category: 'INTERNAL_LININGS',
    subCategory: 'Insulation',
    unit: 'm2',
    materialRate: 22,
    labourRate: 62,
    labourHours: 0.105,
    totalRate: 28.51,
  },
  {
    code: 'INT-06',
    description: 'Wall insulation R2.5 (glasswool batts)',
    category: 'INTERNAL_LININGS',
    subCategory: 'Insulation',
    unit: 'm2',
    materialRate: 15,
    labourRate: 62,
    labourHours: 0.097,
    totalRate: 21.01,
  },

  // === INTERNAL FIT-OUT ===
  {
    code: 'FIT-01',
    description: 'Kitchen cabinetry (mid-range, two-pack polyurethane)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Kitchen',
    unit: 'lm',
    materialRate: 810,
    labourRate: 82,
    labourHours: 1.83,
    totalRate: 960.06,
    notes: 'Base + wall units; excludes benchtop, appliances and plumbing',
  },
  {
    code: 'FIT-02',
    description: 'Stone benchtop 20mm (engineered stone, supply & install)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Kitchen',
    unit: 'lm',
    materialRate: 590,
    labourRate: 90,
    labourHours: 1.0,
    totalRate: 680.00,
    notes: 'Caesarstone or equivalent; includes cutouts, edge profile',
  },
  {
    code: 'FIT-03',
    description: 'Bathroom vanity unit (900mm, wall-hung, stone top)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Bathroom',
    unit: 'each',
    materialRate: 680,
    labourRate: 80,
    labourHours: 2.25,
    totalRate: 860.00,
  },
  {
    code: 'FIT-04',
    description: 'Laundry trough and cabinet (600mm)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Laundry',
    unit: 'each',
    materialRate: 460,
    labourRate: 80,
    labourHours: 1.6,
    totalRate: 588.00,
  },
  {
    code: 'FIT-05',
    description: 'Built-in wardrobe shelving (per lm width)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Robes',
    unit: 'lm',
    materialRate: 220,
    labourRate: 70,
    labourHours: 0.86,
    totalRate: 280.20,
  },
  {
    code: 'FIT-06',
    description: 'Skirting (90mm MDF, supply, fix & prime)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Trim',
    unit: 'lm',
    materialRate: 15,
    labourRate: 58,
    labourHours: 0.09,
    totalRate: 20.22,
  },
  {
    code: 'FIT-07',
    description: 'Architraves (65mm MDF, supply, fix & prime)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Trim',
    unit: 'lm',
    materialRate: 10,
    labourRate: 58,
    labourHours: 0.07,
    totalRate: 14.06,
  },
  {
    code: 'FIT-08',
    description: 'Freestanding bath (acrylic or stone resin, supply & connect)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Bathroom',
    unit: 'each',
    materialRate: 1500,
    labourRate: 80,
    labourHours: 2.5,
    totalRate: 1700.00,
  },
  {
    code: 'FIT-09',
    description: 'Frameless shower screen (10mm toughened glass, 900mm)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Bathroom',
    unit: 'each',
    materialRate: 1350,
    labourRate: 90,
    labourHours: 2.0,
    totalRate: 1530.00,
  },
  {
    code: 'FIT-10',
    description: 'Staircase — timber, 16–18 risers with balustrade (complete)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Stairs',
    unit: 'each',
    materialRate: 8500,
    labourRate: 90,
    labourHours: 36,
    totalRate: 11740.00,
    notes: 'Includes treads, risers, stringers, newel posts, handrail, balustrade',
  },
  {
    code: 'FIT-11',
    description: 'Glass balustrade (semi-frameless, toughened, per lm)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Balustrade',
    unit: 'lm',
    materialRate: 420,
    labourRate: 90,
    labourHours: 1.6,
    totalRate: 564.00,
  },

  // === ELECTRICAL ===
  {
    code: 'ELEC-01',
    description: 'Power point GPO (double, supply & wire)',
    category: 'ELECTRICAL',
    subCategory: 'Power',
    unit: 'each',
    materialRate: 32,
    labourRate: 100,
    labourHours: 0.42,
    totalRate: 74.00,
  },
  {
    code: 'ELEC-02',
    description: 'Double power point DGPO (surface mount)',
    category: 'ELECTRICAL',
    subCategory: 'Power',
    unit: 'each',
    materialRate: 42,
    labourRate: 100,
    labourHours: 0.52,
    totalRate: 94.00,
  },
  {
    code: 'ELEC-03',
    description: 'LED downlight (90mm, dimmable, supply & install)',
    category: 'ELECTRICAL',
    subCategory: 'Lighting',
    unit: 'each',
    materialRate: 58,
    labourRate: 100,
    labourHours: 0.38,
    totalRate: 96.00,
  },
  {
    code: 'ELEC-04',
    description: 'Light point (oyster/pendant fixture)',
    category: 'ELECTRICAL',
    subCategory: 'Lighting',
    unit: 'each',
    materialRate: 95,
    labourRate: 100,
    labourHours: 0.52,
    totalRate: 147.00,
  },
  {
    code: 'ELEC-05',
    description: 'Switch (single or double, supply & wire)',
    category: 'ELECTRICAL',
    subCategory: 'Switches',
    unit: 'each',
    materialRate: 22,
    labourRate: 100,
    labourHours: 0.27,
    totalRate: 49.00,
  },
  {
    code: 'ELEC-06',
    description: 'Smoke detector (240V mains, interconnected)',
    category: 'ELECTRICAL',
    subCategory: 'Safety',
    unit: 'each',
    materialRate: 95,
    labourRate: 100,
    labourHours: 0.52,
    totalRate: 147.00,
    notes: 'NCC 2022 requirement — photoelectric type',
  },
  {
    code: 'ELEC-07',
    description: 'Exhaust fan (inline, bathroom/laundry)',
    category: 'ELECTRICAL',
    subCategory: 'Ventilation',
    unit: 'each',
    materialRate: 145,
    labourRate: 100,
    labourHours: 0.82,
    totalRate: 227.00,
  },
  {
    code: 'ELEC-08',
    description: 'Rangehood connection (240V circuit)',
    category: 'ELECTRICAL',
    subCategory: 'Appliances',
    unit: 'each',
    materialRate: 55,
    labourRate: 100,
    labourHours: 0.52,
    totalRate: 107.00,
  },
  {
    code: 'ELEC-09',
    description: 'Switchboard (MSB, 3-phase capable, RCDs)',
    category: 'ELECTRICAL',
    subCategory: 'Distribution',
    unit: 'each',
    materialRate: 850,
    labourRate: 100,
    labourHours: 5.0,
    totalRate: 1350.00,
    notes: 'Includes metering panel, circuit breakers, RCD/RCBO protection',
  },
  {
    code: 'ELEC-10',
    description: 'Electrical fit-off, test & certification (per lot)',
    category: 'ELECTRICAL',
    subCategory: 'Final',
    unit: 'lot',
    materialRate: 0,
    labourRate: 100,
    labourHours: 10.0,
    totalRate: 1000.00,
  },

  // === PLUMBING ===
  {
    code: 'PLUMB-01',
    description: 'Water supply rough-in (per fixture)',
    category: 'PLUMBING',
    subCategory: 'Rough-in',
    unit: 'each',
    materialRate: 95,
    labourRate: 110,
    labourHours: 1.05,
    totalRate: 210.50,
  },
  {
    code: 'PLUMB-02',
    description: 'Drainage rough-in (per fixture)',
    category: 'PLUMBING',
    subCategory: 'Rough-in',
    unit: 'each',
    materialRate: 130,
    labourRate: 110,
    labourHours: 1.55,
    totalRate: 300.50,
  },
  {
    code: 'PLUMB-03',
    description: 'Toilet suite (wall-faced close coupled)',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 450,
    labourRate: 110,
    labourHours: 2.0,
    totalRate: 670.00,
  },
  {
    code: 'PLUMB-04',
    description: 'Shower mixer and rose (concealed, inc. shower arm)',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 380,
    labourRate: 110,
    labourHours: 1.6,
    totalRate: 556.00,
  },
  {
    code: 'PLUMB-05',
    description: 'Basin mixer tap (wall or deck mount)',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 220,
    labourRate: 110,
    labourHours: 0.82,
    totalRate: 310.20,
  },
  {
    code: 'PLUMB-06',
    description: 'Kitchen sink (undermount stainless, double bowl)',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 420,
    labourRate: 110,
    labourHours: 1.6,
    totalRate: 596.00,
  },
  {
    code: 'PLUMB-07',
    description: 'Kitchen mixer tap (pull-out spray)',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 280,
    labourRate: 110,
    labourHours: 0.82,
    totalRate: 370.20,
  },
  {
    code: 'PLUMB-08',
    description: 'Hot water system (heat pump 270L, supply & connect)',
    category: 'PLUMBING',
    subCategory: 'Hot Water',
    unit: 'each',
    materialRate: 2200,
    labourRate: 110,
    labourHours: 4.5,
    totalRate: 2695.00,
    notes: 'Heat pump preferred 2024; gas storage alternative reduces to ~$2,200',
  },
  {
    code: 'PLUMB-09',
    description: 'Stormwater drainage (site, inc. pits and pipes)',
    category: 'PLUMBING',
    subCategory: 'Drainage',
    unit: 'lot',
    materialRate: 2200,
    labourRate: 110,
    labourHours: 14.0,
    totalRate: 3740.00,
  },
  {
    code: 'PLUMB-10',
    description: 'Sewer connection (to existing main)',
    category: 'PLUMBING',
    subCategory: 'Drainage',
    unit: 'lot',
    materialRate: 1200,
    labourRate: 110,
    labourHours: 9.0,
    totalRate: 2190.00,
  },

  // === HVAC ===
  {
    code: 'HVAC-01',
    description: 'Split system air conditioning (8kW, supply & install)',
    category: 'HVAC',
    subCategory: 'Air Conditioning',
    unit: 'each',
    materialRate: 1750,
    labourRate: 95,
    labourHours: 4.8,
    totalRate: 2206.00,
    notes: 'Mitsubishi/Daikin/Fujitsu 8kW; includes electrical connection',
  },
  {
    code: 'HVAC-02',
    description: 'Ducted air conditioning (whole house, 14kW)',
    category: 'HVAC',
    subCategory: 'Air Conditioning',
    unit: 'lot',
    materialRate: 12000,
    labourRate: 95,
    labourHours: 28.0,
    totalRate: 14660.00,
  },
  {
    code: 'HVAC-03',
    description: 'Gas heater point (outlet only)',
    category: 'HVAC',
    subCategory: 'Heating',
    unit: 'each',
    materialRate: 520,
    labourRate: 95,
    labourHours: 3.2,
    totalRate: 824.00,
  },

  // === PAINTING ===
  {
    code: 'PAINT-01',
    description: 'Internal walls (2 coats low sheen, inc. prep)',
    category: 'PAINTING',
    subCategory: 'Internal',
    unit: 'm2',
    materialRate: 10,
    labourRate: 62,
    labourHours: 0.23,
    totalRate: 24.26,
    notes: 'Supply & apply Dulux or equivalent; includes patch, sand, 2 coats',
  },
  {
    code: 'PAINT-02',
    description: 'Internal ceilings (2 coats flat white, inc. prep)',
    category: 'PAINTING',
    subCategory: 'Internal',
    unit: 'm2',
    materialRate: 8,
    labourRate: 62,
    labourHours: 0.185,
    totalRate: 19.47,
  },
  {
    code: 'PAINT-03',
    description: 'Internal doors and frames (per door)',
    category: 'PAINTING',
    subCategory: 'Internal',
    unit: 'each',
    materialRate: 30,
    labourRate: 62,
    labourHours: 0.82,
    totalRate: 80.84,
  },
  {
    code: 'PAINT-04',
    description: 'External rendered/Hebel walls (2 coats exterior)',
    category: 'PAINTING',
    subCategory: 'External',
    unit: 'm2',
    materialRate: 14,
    labourRate: 65,
    labourHours: 0.28,
    totalRate: 32.20,
  },

  // === FLOOR COVERINGS ===
  {
    code: 'FLOOR-01',
    description: 'Floor tiles — porcelain 600×600mm (supply, lay, grout)',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Tiling',
    unit: 'm2',
    materialRate: 88,
    labourRate: 75,
    labourHours: 0.67,
    totalRate: 138.25,
    notes: 'Mid-range porcelain; includes 10% waste, adhesive, grout, sealant',
  },
  {
    code: 'FLOOR-02',
    description: 'Wall tiles — ceramic 300×600mm (supply, lay, grout)',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Tiling',
    unit: 'm2',
    materialRate: 72,
    labourRate: 75,
    labourHours: 0.62,
    totalRate: 118.50,
  },
  {
    code: 'FLOOR-03',
    description: 'Carpet (Wool blend, mid-range) with 10mm underlay',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Soft Flooring',
    unit: 'm2',
    materialRate: 65,
    labourRate: 50,
    labourHours: 0.18,
    totalRate: 74.00,
  },
  {
    code: 'FLOOR-04',
    description: 'Engineered timber flooring (14mm, floating)',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Hard Flooring',
    unit: 'm2',
    materialRate: 115,
    labourRate: 62,
    labourHours: 0.53,
    totalRate: 147.86,
    notes: 'European oak or similar; inc. underlay, adhesive, beading',
  },
  {
    code: 'FLOOR-05',
    description: 'Vinyl plank flooring (5mm SPC, click-lock)',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Hard Flooring',
    unit: 'm2',
    materialRate: 58,
    labourRate: 58,
    labourHours: 0.34,
    totalRate: 77.72,
  },

  // === EXTERNAL WORKS ===
  {
    code: 'EXTW-01',
    description: 'Concrete paths and driveways (100mm mesh reinforced)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Paving',
    unit: 'm2',
    materialRate: 58,
    labourRate: 80,
    labourHours: 0.28,
    totalRate: 80.40,
  },
  {
    code: 'EXTW-02',
    description: 'Timber decking (hardwood 90×19mm treated)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Decking',
    unit: 'm2',
    materialRate: 145,
    labourRate: 80,
    labourHours: 0.55,
    totalRate: 189.00,
  },
  {
    code: 'EXTW-03',
    description: 'Colorbond fencing (1.8m high, inc. posts)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Fencing',
    unit: 'lm',
    materialRate: 110,
    labourRate: 70,
    labourHours: 0.32,
    totalRate: 132.40,
  },
  {
    code: 'EXTW-04',
    description: 'Retaining wall (200×200mm concrete sleeper)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Retaining',
    unit: 'm2',
    materialRate: 210,
    labourRate: 80,
    labourHours: 0.9,
    totalRate: 282.00,
  },
  {
    code: 'EXTW-05',
    description: 'Letterbox (brick, tiled top)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Misc',
    unit: 'each',
    materialRate: 420,
    labourRate: 80,
    labourHours: 4.5,
    totalRate: 780.00,
  },
  {
    code: 'EXTW-06',
    description: 'Clothesline (Hills Hoist or fold-down)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Misc',
    unit: 'each',
    materialRate: 220,
    labourRate: 70,
    labourHours: 1.1,
    totalRate: 297.00,
  },
  {
    code: 'EXTW-07',
    description: 'Carport structure (posts, beams, Colorbond roof)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Carport',
    unit: 'm2',
    materialRate: 210,
    labourRate: 90,
    labourHours: 0.78,
    totalRate: 280.20,
  },
  {
    code: 'EXTW-08',
    description: 'Aluminium gate and intercom system',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Access',
    unit: 'item',
    materialRate: 2800,
    labourRate: 80,
    labourHours: 7.0,
    totalRate: 3360.00,
  },
  {
    code: 'EXTW-09',
    description: 'Pool surrounds / paved area',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Pool',
    unit: 'm2',
    materialRate: 110,
    labourRate: 80,
    labourHours: 0.48,
    totalRate: 148.40,
  },
  {
    code: 'EXTW-10',
    description: 'Termite management (chemical soil treatment, AS 3660)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Compliance',
    unit: 'lot',
    materialRate: 1800,
    labourRate: 80,
    labourHours: 8.0,
    totalRate: 2440.00,
    notes: 'Required by NCC for all new class 1 dwellings; per building footprint',
  },

  // === POOLS ===
  {
    code: 'POOL-01',
    description: 'Inground concrete pool — complete (excavation, shell, tiling, filtration, pump)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Pool',
    unit: 'item',
    materialRate: 52000,
    labourRate: 90,
    labourHours: 220,
    totalRate: 71800.00,
    notes: 'Typical 6×3m pool with salt chlorinator; adjust for size',
  },
  {
    code: 'POOL-02',
    description: 'Glass pool fencing (frameless toughened, AS 1926)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Pool',
    unit: 'lm',
    materialRate: 340,
    labourRate: 80,
    labourHours: 1.1,
    totalRate: 428.00,
  },

  // === CERTIFICATIONS ===
  {
    code: 'CERT-01',
    description: 'Building permit and inspections (Class 1 dwelling)',
    category: 'CERTIFICATIONS',
    subCategory: 'Council',
    unit: 'lot',
    materialRate: 8000,
    labourRate: 0,
    labourHours: 0,
    totalRate: 8000.00,
    notes: 'DA + CDC + mandatory inspections; duplex: multiply by 1.8',
  },
  {
    code: 'CERT-02',
    description: 'Engineering certification (structural, geotechnical)',
    category: 'CERTIFICATIONS',
    subCategory: 'Engineering',
    unit: 'lot',
    materialRate: 3500,
    labourRate: 0,
    labourHours: 0,
    totalRate: 3500.00,
  },
  {
    code: 'CERT-03',
    description: 'Energy rating certificate NatHERS (per dwelling)',
    category: 'CERTIFICATIONS',
    subCategory: 'Compliance',
    unit: 'lot',
    materialRate: 650,
    labourRate: 0,
    labourHours: 0,
    totalRate: 650.00,
  },
  {
    code: 'CERT-04',
    description: 'Survey and setout (registered surveyor)',
    category: 'CERTIFICATIONS',
    subCategory: 'Survey',
    unit: 'lot',
    materialRate: 1800,
    labourRate: 0,
    labourHours: 0,
    totalRate: 1800.00,
  },
  {
    code: 'CERT-05',
    description: 'Final inspection and occupancy certificate (per dwelling)',
    category: 'CERTIFICATIONS',
    subCategory: 'Final',
    unit: 'lot',
    materialRate: 950,
    labourRate: 0,
    labourHours: 0,
    totalRate: 950.00,
  },
];

// Helper function to get rate by code
export function getRateByCode(code: string): ConstructionRate | undefined {
  return AUSTRALIAN_CONSTRUCTION_RATES.find(r => r.code === code);
}

// Helper function to get rates by category
export function getRatesByCategory(category: SOWCategory): ConstructionRate[] {
  return AUSTRALIAN_CONSTRUCTION_RATES.filter(r => r.category === category);
}

// Typical house cost range for sanity check (2024 AUD, construction cost only, excl. land)
export function calculateTypicalHouseCost(floorAreaM2: number): { low: number; mid: number; high: number } {
  // Budget: $2,000–2,400/m²
  // Mid-range: $2,400–3,200/m²
  // High-end: $3,200–4,800/m²
  return {
    low: Math.round(floorAreaM2 * 2100),
    mid: Math.round(floorAreaM2 * 2800),
    high: Math.round(floorAreaM2 * 3800),
  };
}

export const DEFAULT_OVERHEADS = {
  siteOverheads: 8,
  companyOverheads: 5,
  contingency: 5,
  margin: 10,
};
