// Australian Residential Construction Rates 2024
// Based on Rawlinsons Australian Construction Handbook and industry data
// All rates in AUD, quantities in metric

export interface ConstructionRate {
  code: string;
  description: string;
  category: SOWCategory;
  subCategory: string;
  unit: 'm2' | 'm' | 'each' | 'item' | 'lm' | 'm3' | 'kg' | 'hr' | 'lot';
  materialRate: number;  // $ per unit
  labourRate: number;    // $ per hour
  labourHours: number;   // hours per unit
  totalRate: number;     // total $ per unit
  notes?: string;
}

// Schedule of Works Categories
export type SOWCategory =
  | 'PRELIMINARIES'
  | 'SITE_WORKS'
  | 'STRUCTURE'
  | 'FRAMING_TRUSS'
  | 'EXTERNAL'
  | 'ROOFING'
  | 'WINDOWS_DOORS'
  | 'INTERNAL_LININGS'
  | 'INTERNAL_FIT_OUT'
  | 'ELECTRICAL'
  | 'PLUMBING'
  | 'HVAC'
  | 'PAINTING'
  | 'FLOOR_COVERINGS'
  | 'EXTERNAL_WORKS'
  | 'CERTIFICATIONS';

export const SOW_CATEGORY_LABELS: Record<SOWCategory, string> = {
  PRELIMINARIES: 'Preliminaries',
  SITE_WORKS: 'Site Works',
  STRUCTURE: 'Structure (Slab & Foundations)',
  FRAMING_TRUSS: 'Framing & Truss',
  EXTERNAL: 'External Cladding & Masonry',
  ROOFING: 'Roofing',
  WINDOWS_DOORS: 'Windows & Doors',
  INTERNAL_LININGS: 'Internal Linings',
  INTERNAL_FIT_OUT: 'Internal Fit-out & Joinery',
  ELECTRICAL: 'Electrical',
  PLUMBING: 'Plumbing & Drainage',
  HVAC: 'HVAC / Mechanical',
  PAINTING: 'Painting',
  FLOOR_COVERINGS: 'Floor Coverings',
  EXTERNAL_WORKS: 'External Works & Landscaping',
  CERTIFICATIONS: 'Certifications & Compliance',
};

// Category display order
export const SOW_CATEGORY_ORDER: SOWCategory[] = [
  'PRELIMINARIES',
  'SITE_WORKS',
  'STRUCTURE',
  'FRAMING_TRUSS',
  'ROOFING',
  'EXTERNAL',
  'WINDOWS_DOORS',
  'INTERNAL_LININGS',
  'INTERNAL_FIT_OUT',
  'ELECTRICAL',
  'PLUMBING',
  'HVAC',
  'PAINTING',
  'FLOOR_COVERINGS',
  'EXTERNAL_WORKS',
  'CERTIFICATIONS',
];

// Construction rates - realistic 2024 Australian residential pricing
export const AUSTRALIAN_CONSTRUCTION_RATES: ConstructionRate[] = [
  // === PRELIMINARIES ===
  {
    code: 'PRELIM-01',
    description: 'Site establishment and temporary facilities',
    category: 'PRELIMINARIES',
    subCategory: 'Setup',
    unit: 'lot',
    materialRate: 2500,
    labourRate: 65,
    labourHours: 16,
    totalRate: 3540,
  },
  {
    code: 'PRELIM-02',
    description: 'Site office and amenities',
    category: 'PRELIMINARIES',
    subCategory: 'Setup',
    unit: 'lot',
    materialRate: 1500,
    labourRate: 65,
    labourHours: 8,
    totalRate: 2020,
  },
  {
    code: 'PRELIM-03',
    description: 'Temporary fencing and hoarding',
    category: 'PRELIMINARIES',
    subCategory: 'Protection',
    unit: 'lm',
    materialRate: 45,
    labourRate: 55,
    labourHours: 0.15,
    totalRate: 53.25,
  },

  // === SITE WORKS ===
  {
    code: 'SITE-01',
    description: 'Site clearing and stripping',
    category: 'SITE_WORKS',
    subCategory: 'Earthworks',
    unit: 'm2',
    materialRate: 0,
    labourRate: 85,
    labourHours: 0.02,
    totalRate: 1.70,
  },
  {
    code: 'SITE-02',
    description: 'Cut and fill earthworks (average)',
    category: 'SITE_WORKS',
    subCategory: 'Earthworks',
    unit: 'm3',
    materialRate: 0,
    labourRate: 95,
    labourHours: 0.25,
    totalRate: 23.75,
  },
  {
    code: 'SITE-03',
    description: 'Compacted fill to building pad',
    category: 'SITE_WORKS',
    subCategory: 'Earthworks',
    unit: 'm3',
    materialRate: 35,
    labourRate: 85,
    labourHours: 0.15,
    totalRate: 47.75,
  },

  // === STRUCTURE ===
  {
    code: 'STRUCT-01',
    description: 'Waffle pod slab on ground (standard residential)',
    category: 'STRUCTURE',
    subCategory: 'Slab',
    unit: 'm2',
    materialRate: 85,
    labourRate: 85,
    labourHours: 0.35,
    totalRate: 114.75,
    notes: 'Includes mesh, vapour barrier, edge beams',
  },
  {
    code: 'STRUCT-02',
    description: 'Raft slab on ground (M class)',
    category: 'STRUCTURE',
    subCategory: 'Slab',
    unit: 'm2',
    materialRate: 110,
    labourRate: 85,
    labourHours: 0.45,
    totalRate: 148.25,
  },
  {
    code: 'STRUCT-03',
    description: 'Strip footings',
    category: 'STRUCTURE',
    subCategory: 'Footings',
    unit: 'lm',
    materialRate: 65,
    labourRate: 85,
    labourHours: 0.5,
    totalRate: 107.50,
  },
  {
    code: 'STRUCT-04',
    description: 'Concrete driveway 100mm',
    category: 'STRUCTURE',
    subCategory: 'Concrete',
    unit: 'm2',
    materialRate: 45,
    labourRate: 75,
    labourHours: 0.25,
    totalRate: 63.75,
  },

  // === FRAMING & TRUSS ===
  {
    code: 'FRAME-01',
    description: 'Timber wall framing (90x45 studs @ 450cc)',
    category: 'FRAMING_TRUSS',
    subCategory: 'Wall Framing',
    unit: 'm2',
    materialRate: 38,
    labourRate: 75,
    labourHours: 0.35,
    totalRate: 64.25,
  },
  {
    code: 'FRAME-02',
    description: 'Steel wall framing (light gauge)',
    category: 'FRAMING_TRUSS',
    subCategory: 'Wall Framing',
    unit: 'm2',
    materialRate: 55,
    labourRate: 85,
    labourHours: 0.4,
    totalRate: 89.00,
  },
  {
    code: 'FRAME-03',
    description: 'Roof trusses (standard residential)',
    category: 'FRAMING_TRUSS',
    subCategory: 'Roof Framing',
    unit: 'm2',
    materialRate: 45,
    labourRate: 75,
    labourHours: 0.3,
    totalRate: 67.50,
    notes: 'Price per m² of floor area covered',
  },
  {
    code: 'FRAME-04',
    description: 'Ceiling joists/battens',
    category: 'FRAMING_TRUSS',
    subCategory: 'Ceiling Framing',
    unit: 'm2',
    materialRate: 18,
    labourRate: 65,
    labourHours: 0.15,
    totalRate: 27.75,
  },
  {
    code: 'FRAME-05',
    description: 'Floor framing (timber, upper level)',
    category: 'FRAMING_TRUSS',
    subCategory: 'Floor Framing',
    unit: 'm2',
    materialRate: 65,
    labourRate: 75,
    labourHours: 0.45,
    totalRate: 98.75,
  },

  // === ROOFING ===
  {
    code: 'ROOF-01',
    description: 'Colorbond roofing (Trimdek/Custom Orb)',
    category: 'ROOFING',
    subCategory: 'Roof Covering',
    unit: 'm2',
    materialRate: 35,
    labourRate: 80,
    labourHours: 0.25,
    totalRate: 55.00,
  },
  {
    code: 'ROOF-02',
    description: 'Concrete roof tiles',
    category: 'ROOFING',
    subCategory: 'Roof Covering',
    unit: 'm2',
    materialRate: 55,
    labourRate: 75,
    labourHours: 0.4,
    totalRate: 85.00,
  },
  {
    code: 'ROOF-03',
    description: 'Sarking/building wrap',
    category: 'ROOFING',
    subCategory: 'Roof Covering',
    unit: 'm2',
    materialRate: 8,
    labourRate: 55,
    labourHours: 0.05,
    totalRate: 10.75,
  },
  {
    code: 'ROOF-04',
    description: 'Fascia and barge boards (Colorbond)',
    category: 'ROOFING',
    subCategory: 'Fascia/Gutters',
    unit: 'lm',
    materialRate: 25,
    labourRate: 65,
    labourHours: 0.2,
    totalRate: 38.00,
  },
  {
    code: 'ROOF-05',
    description: 'Gutters (Colorbond quad)',
    category: 'ROOFING',
    subCategory: 'Fascia/Gutters',
    unit: 'lm',
    materialRate: 18,
    labourRate: 65,
    labourHours: 0.15,
    totalRate: 27.75,
  },
  {
    code: 'ROOF-06',
    description: 'Downpipes (Colorbond 90mm)',
    category: 'ROOFING',
    subCategory: 'Fascia/Gutters',
    unit: 'lm',
    materialRate: 22,
    labourRate: 65,
    labourHours: 0.2,
    totalRate: 35.00,
  },

  // === EXTERNAL ===
  {
    code: 'EXT-01',
    description: 'Brick veneer (standard face brick)',
    category: 'EXTERNAL',
    subCategory: 'Masonry',
    unit: 'm2',
    materialRate: 75,
    labourRate: 85,
    labourHours: 0.8,
    totalRate: 143.00,
  },
  {
    code: 'EXT-02',
    description: 'Hebel PowerPanel 75mm',
    category: 'EXTERNAL',
    subCategory: 'Cladding',
    unit: 'm2',
    materialRate: 65,
    labourRate: 75,
    labourHours: 0.35,
    totalRate: 91.25,
  },
  {
    code: 'EXT-03',
    description: 'Weatherboard cladding (fibre cement)',
    category: 'EXTERNAL',
    subCategory: 'Cladding',
    unit: 'm2',
    materialRate: 45,
    labourRate: 75,
    labourHours: 0.4,
    totalRate: 75.00,
  },
  {
    code: 'EXT-04',
    description: 'Render to masonry (acrylic)',
    category: 'EXTERNAL',
    subCategory: 'Render',
    unit: 'm2',
    materialRate: 25,
    labourRate: 70,
    labourHours: 0.35,
    totalRate: 49.50,
  },

  // === WINDOWS & DOORS ===
  {
    code: 'WD-01',
    description: 'Aluminium sliding window (standard)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Windows',
    unit: 'each',
    materialRate: 380,
    labourRate: 75,
    labourHours: 1.0,
    totalRate: 455.00,
    notes: 'Average 1200x1200mm',
  },
  {
    code: 'WD-02',
    description: 'Aluminium awning window',
    category: 'WINDOWS_DOORS',
    subCategory: 'Windows',
    unit: 'each',
    materialRate: 320,
    labourRate: 75,
    labourHours: 1.0,
    totalRate: 395.00,
  },
  {
    code: 'WD-03',
    description: 'Large sliding door (2.4m wide)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Windows',
    unit: 'each',
    materialRate: 1200,
    labourRate: 85,
    labourHours: 2.5,
    totalRate: 1412.50,
  },
  {
    code: 'WD-04',
    description: 'Internal door (hollow core) with frame & hardware',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 280,
    labourRate: 75,
    labourHours: 1.5,
    totalRate: 392.50,
  },
  {
    code: 'WD-05',
    description: 'Internal door (solid core) with frame & hardware',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 450,
    labourRate: 75,
    labourHours: 1.5,
    totalRate: 562.50,
  },
  {
    code: 'WD-06',
    description: 'External entry door (solid core) with frame & hardware',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 850,
    labourRate: 85,
    labourHours: 2.5,
    totalRate: 1062.50,
  },
  {
    code: 'WD-07',
    description: 'Garage door (sectional) single',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 1400,
    labourRate: 85,
    labourHours: 4.0,
    totalRate: 1740.00,
  },
  {
    code: 'WD-08',
    description: 'Garage door (sectional) double',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'each',
    materialRate: 2200,
    labourRate: 85,
    labourHours: 5.0,
    totalRate: 2625.00,
  },
  {
    code: 'WD-09',
    description: 'Sliding wardrobe doors (mirrored)',
    category: 'WINDOWS_DOORS',
    subCategory: 'Doors',
    unit: 'lm',
    materialRate: 280,
    labourRate: 75,
    labourHours: 0.5,
    totalRate: 317.50,
  },

  // === INTERNAL LININGS ===
  {
    code: 'INT-01',
    description: 'Plasterboard walls (10mm standard)',
    category: 'INTERNAL_LININGS',
    subCategory: 'Walls',
    unit: 'm2',
    materialRate: 18,
    labourRate: 65,
    labourHours: 0.25,
    totalRate: 34.25,
    notes: 'Includes fixing and stopping',
  },
  {
    code: 'INT-02',
    description: 'Plasterboard ceiling (10mm)',
    category: 'INTERNAL_LININGS',
    subCategory: 'Ceilings',
    unit: 'm2',
    materialRate: 20,
    labourRate: 65,
    labourHours: 0.3,
    totalRate: 39.50,
  },
  {
    code: 'INT-03',
    description: 'Villaboard wet area (wet rooms)',
    category: 'INTERNAL_LININGS',
    subCategory: 'Wet Areas',
    unit: 'm2',
    materialRate: 35,
    labourRate: 65,
    labourHours: 0.35,
    totalRate: 57.75,
  },
  {
    code: 'INT-04',
    description: 'Wet area waterproofing membrane',
    category: 'INTERNAL_LININGS',
    subCategory: 'Wet Areas',
    unit: 'm2',
    materialRate: 25,
    labourRate: 65,
    labourHours: 0.3,
    totalRate: 44.50,
  },
  {
    code: 'INT-05',
    description: 'Ceiling insulation R4.0',
    category: 'INTERNAL_LININGS',
    subCategory: 'Insulation',
    unit: 'm2',
    materialRate: 18,
    labourRate: 55,
    labourHours: 0.08,
    totalRate: 22.40,
  },
  {
    code: 'INT-06',
    description: 'Wall insulation R2.5',
    category: 'INTERNAL_LININGS',
    subCategory: 'Insulation',
    unit: 'm2',
    materialRate: 12,
    labourRate: 55,
    labourHours: 0.05,
    totalRate: 14.75,
  },

  // === INTERNAL FIT-OUT ===
  {
    code: 'FIT-01',
    description: 'Kitchen cabinetry (standard)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Kitchen',
    unit: 'lm',
    materialRate: 650,
    labourRate: 75,
    labourHours: 2.0,
    totalRate: 800.00,
    notes: 'Base and wall units, laminate doors',
  },
  {
    code: 'FIT-02',
    description: 'Stone benchtop (20mm)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Kitchen',
    unit: 'lm',
    materialRate: 450,
    labourRate: 85,
    labourHours: 1.0,
    totalRate: 535.00,
  },
  {
    code: 'FIT-03',
    description: 'Bathroom vanity unit (900mm)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Bathroom',
    unit: 'each',
    materialRate: 550,
    labourRate: 75,
    labourHours: 2.0,
    totalRate: 700.00,
  },
  {
    code: 'FIT-04',
    description: 'Laundry trough and cabinet',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Laundry',
    unit: 'each',
    materialRate: 380,
    labourRate: 75,
    labourHours: 1.5,
    totalRate: 492.50,
  },
  {
    code: 'FIT-05',
    description: 'Built-in wardrobe shelving',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Robes',
    unit: 'lm',
    materialRate: 180,
    labourRate: 65,
    labourHours: 0.75,
    totalRate: 228.75,
  },
  {
    code: 'FIT-06',
    description: 'Skirting (90mm MDF)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Trim',
    unit: 'lm',
    materialRate: 12,
    labourRate: 55,
    labourHours: 0.08,
    totalRate: 16.40,
  },
  {
    code: 'FIT-07',
    description: 'Architraves (65mm MDF)',
    category: 'INTERNAL_FIT_OUT',
    subCategory: 'Trim',
    unit: 'lm',
    materialRate: 8,
    labourRate: 55,
    labourHours: 0.06,
    totalRate: 11.30,
  },

  // === ELECTRICAL ===
  {
    code: 'ELEC-01',
    description: 'Power point (GPO)',
    category: 'ELECTRICAL',
    subCategory: 'Power',
    unit: 'each',
    materialRate: 25,
    labourRate: 95,
    labourHours: 0.4,
    totalRate: 63.00,
  },
  {
    code: 'ELEC-02',
    description: 'Double power point (DGPO)',
    category: 'ELECTRICAL',
    subCategory: 'Power',
    unit: 'each',
    materialRate: 35,
    labourRate: 95,
    labourHours: 0.5,
    totalRate: 82.50,
  },
  {
    code: 'ELEC-03',
    description: 'Light point (downlight LED)',
    category: 'ELECTRICAL',
    subCategory: 'Lighting',
    unit: 'each',
    materialRate: 45,
    labourRate: 95,
    labourHours: 0.35,
    totalRate: 78.25,
  },
  {
    code: 'ELEC-04',
    description: 'Light point (oyster/pendant)',
    category: 'ELECTRICAL',
    subCategory: 'Lighting',
    unit: 'each',
    materialRate: 85,
    labourRate: 95,
    labourHours: 0.5,
    totalRate: 132.50,
  },
  {
    code: 'ELEC-05',
    description: 'Switch (single)',
    category: 'ELECTRICAL',
    subCategory: 'Switches',
    unit: 'each',
    materialRate: 18,
    labourRate: 95,
    labourHours: 0.25,
    totalRate: 41.75,
  },
  {
    code: 'ELEC-06',
    description: 'Smoke detector (mains powered)',
    category: 'ELECTRICAL',
    subCategory: 'Safety',
    unit: 'each',
    materialRate: 85,
    labourRate: 95,
    labourHours: 0.5,
    totalRate: 132.50,
  },
  {
    code: 'ELEC-07',
    description: 'Exhaust fan (bathroom)',
    category: 'ELECTRICAL',
    subCategory: 'Ventilation',
    unit: 'each',
    materialRate: 120,
    labourRate: 95,
    labourHours: 0.75,
    totalRate: 191.25,
  },
  {
    code: 'ELEC-08',
    description: 'Rangehood connection',
    category: 'ELECTRICAL',
    subCategory: 'Appliances',
    unit: 'each',
    materialRate: 50,
    labourRate: 95,
    labourHours: 0.5,
    totalRate: 97.50,
  },
  {
    code: 'ELEC-09',
    description: 'Switchboard (residential)',
    category: 'ELECTRICAL',
    subCategory: 'Distribution',
    unit: 'each',
    materialRate: 650,
    labourRate: 95,
    labourHours: 4.0,
    totalRate: 1030.00,
  },
  {
    code: 'ELEC-10',
    description: 'Electrical fit-off and testing',
    category: 'ELECTRICAL',
    subCategory: 'Final',
    unit: 'lot',
    materialRate: 0,
    labourRate: 95,
    labourHours: 8.0,
    totalRate: 760.00,
  },

  // === PLUMBING ===
  {
    code: 'PLUMB-01',
    description: 'Water supply rough-in (per fixture)',
    category: 'PLUMBING',
    subCategory: 'Rough-in',
    unit: 'each',
    materialRate: 85,
    labourRate: 100,
    labourHours: 1.0,
    totalRate: 185.00,
  },
  {
    code: 'PLUMB-02',
    description: 'Drainage rough-in (per fixture)',
    category: 'PLUMBING',
    subCategory: 'Rough-in',
    unit: 'each',
    materialRate: 120,
    labourRate: 100,
    labourHours: 1.5,
    totalRate: 270.00,
  },
  {
    code: 'PLUMB-03',
    description: 'Toilet suite (close coupled)',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 380,
    labourRate: 100,
    labourHours: 2.0,
    totalRate: 580.00,
  },
  {
    code: 'PLUMB-04',
    description: 'Shower mixer and rose',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 280,
    labourRate: 100,
    labourHours: 1.5,
    totalRate: 430.00,
  },
  {
    code: 'PLUMB-05',
    description: 'Basin mixer tap',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 180,
    labourRate: 100,
    labourHours: 0.75,
    totalRate: 255.00,
  },
  {
    code: 'PLUMB-06',
    description: 'Kitchen sink (double bowl stainless)',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 350,
    labourRate: 100,
    labourHours: 1.5,
    totalRate: 500.00,
  },
  {
    code: 'PLUMB-07',
    description: 'Kitchen mixer tap',
    category: 'PLUMBING',
    subCategory: 'Fixtures',
    unit: 'each',
    materialRate: 220,
    labourRate: 100,
    labourHours: 0.75,
    totalRate: 295.00,
  },
  {
    code: 'PLUMB-08',
    description: 'Hot water system (gas storage 170L)',
    category: 'PLUMBING',
    subCategory: 'Hot Water',
    unit: 'each',
    materialRate: 1400,
    labourRate: 100,
    labourHours: 4.0,
    totalRate: 1800.00,
  },
  {
    code: 'PLUMB-09',
    description: 'Stormwater drainage (site)',
    category: 'PLUMBING',
    subCategory: 'Drainage',
    unit: 'lot',
    materialRate: 1500,
    labourRate: 100,
    labourHours: 12.0,
    totalRate: 2700.00,
  },
  {
    code: 'PLUMB-10',
    description: 'Sewer connection',
    category: 'PLUMBING',
    subCategory: 'Drainage',
    unit: 'lot',
    materialRate: 800,
    labourRate: 100,
    labourHours: 8.0,
    totalRate: 1600.00,
  },

  // === HVAC ===
  {
    code: 'HVAC-01',
    description: 'Split system air conditioning (per unit)',
    category: 'HVAC',
    subCategory: 'Air Conditioning',
    unit: 'each',
    materialRate: 1200,
    labourRate: 90,
    labourHours: 4.0,
    totalRate: 1560.00,
  },
  {
    code: 'HVAC-02',
    description: 'Ducted air conditioning (whole house)',
    category: 'HVAC',
    subCategory: 'Air Conditioning',
    unit: 'lot',
    materialRate: 8500,
    labourRate: 90,
    labourHours: 24.0,
    totalRate: 10660.00,
  },
  {
    code: 'HVAC-03',
    description: 'Gas heater point',
    category: 'HVAC',
    subCategory: 'Heating',
    unit: 'each',
    materialRate: 450,
    labourRate: 90,
    labourHours: 3.0,
    totalRate: 720.00,
  },

  // === PAINTING ===
  {
    code: 'PAINT-01',
    description: 'Internal walls (2 coats)',
    category: 'PAINTING',
    subCategory: 'Internal',
    unit: 'm2',
    materialRate: 6,
    labourRate: 55,
    labourHours: 0.12,
    totalRate: 12.60,
  },
  {
    code: 'PAINT-02',
    description: 'Internal ceilings (2 coats)',
    category: 'PAINTING',
    subCategory: 'Internal',
    unit: 'm2',
    materialRate: 5,
    labourRate: 55,
    labourHours: 0.1,
    totalRate: 10.50,
  },
  {
    code: 'PAINT-03',
    description: 'Internal doors and frames',
    category: 'PAINTING',
    subCategory: 'Internal',
    unit: 'each',
    materialRate: 25,
    labourRate: 55,
    labourHours: 0.75,
    totalRate: 66.25,
  },
  {
    code: 'PAINT-04',
    description: 'External walls (render/hebel)',
    category: 'PAINTING',
    subCategory: 'External',
    unit: 'm2',
    materialRate: 8,
    labourRate: 60,
    labourHours: 0.15,
    totalRate: 17.00,
  },

  // === FLOOR COVERINGS ===
  {
    code: 'FLOOR-01',
    description: 'Floor tiles (porcelain) with adhesive',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Tiling',
    unit: 'm2',
    materialRate: 65,
    labourRate: 70,
    labourHours: 0.6,
    totalRate: 107.00,
  },
  {
    code: 'FLOOR-02',
    description: 'Wall tiles (ceramic) with adhesive',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Tiling',
    unit: 'm2',
    materialRate: 55,
    labourRate: 70,
    labourHours: 0.5,
    totalRate: 90.00,
  },
  {
    code: 'FLOOR-03',
    description: 'Carpet (mid-range) with underlay',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Soft Flooring',
    unit: 'm2',
    materialRate: 55,
    labourRate: 45,
    labourHours: 0.15,
    totalRate: 61.75,
  },
  {
    code: 'FLOOR-04',
    description: 'Engineered timber flooring',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Hard Flooring',
    unit: 'm2',
    materialRate: 85,
    labourRate: 55,
    labourHours: 0.25,
    totalRate: 98.75,
  },
  {
    code: 'FLOOR-05',
    description: 'Vinyl plank flooring',
    category: 'FLOOR_COVERINGS',
    subCategory: 'Hard Flooring',
    unit: 'm2',
    materialRate: 45,
    labourRate: 45,
    labourHours: 0.2,
    totalRate: 54.00,
  },

  // === EXTERNAL WORKS ===
  {
    code: 'EXTW-01',
    description: 'Concrete paths (100mm)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Paving',
    unit: 'm2',
    materialRate: 45,
    labourRate: 75,
    labourHours: 0.25,
    totalRate: 63.75,
  },
  {
    code: 'EXTW-02',
    description: 'Timber decking (treated pine)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Decking',
    unit: 'm2',
    materialRate: 120,
    labourRate: 75,
    labourHours: 0.5,
    totalRate: 157.50,
  },
  {
    code: 'EXTW-03',
    description: 'Colorbond fencing (1.8m high)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Fencing',
    unit: 'lm',
    materialRate: 95,
    labourRate: 65,
    labourHours: 0.3,
    totalRate: 114.50,
  },
  {
    code: 'EXTW-04',
    description: 'Retaining wall (sleeper)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Retaining',
    unit: 'm2',
    materialRate: 180,
    labourRate: 75,
    labourHours: 0.8,
    totalRate: 240.00,
  },
  {
    code: 'EXTW-05',
    description: 'Letterbox (brick)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Misc',
    unit: 'each',
    materialRate: 350,
    labourRate: 75,
    labourHours: 4.0,
    totalRate: 650.00,
  },
  {
    code: 'EXTW-06',
    description: 'Clothesline (fold down)',
    category: 'EXTERNAL_WORKS',
    subCategory: 'Misc',
    unit: 'each',
    materialRate: 180,
    labourRate: 65,
    labourHours: 1.0,
    totalRate: 245.00,
  },

  // === CERTIFICATIONS ===
  {
    code: 'CERT-01',
    description: 'Building permit and inspections',
    category: 'CERTIFICATIONS',
    subCategory: 'Council',
    unit: 'lot',
    materialRate: 2500,
    labourRate: 0,
    labourHours: 0,
    totalRate: 2500.00,
  },
  {
    code: 'CERT-02',
    description: 'Engineering certification',
    category: 'CERTIFICATIONS',
    subCategory: 'Engineering',
    unit: 'lot',
    materialRate: 1800,
    labourRate: 0,
    labourHours: 0,
    totalRate: 1800.00,
  },
  {
    code: 'CERT-03',
    description: 'Energy rating certificate (NatHERS)',
    category: 'CERTIFICATIONS',
    subCategory: 'Compliance',
    unit: 'lot',
    materialRate: 450,
    labourRate: 0,
    labourHours: 0,
    totalRate: 450.00,
  },
  {
    code: 'CERT-04',
    description: 'Survey and setout',
    category: 'CERTIFICATIONS',
    subCategory: 'Survey',
    unit: 'lot',
    materialRate: 850,
    labourRate: 0,
    labourHours: 0,
    totalRate: 850.00,
  },
  {
    code: 'CERT-05',
    description: 'Final inspection and occupancy certificate',
    category: 'CERTIFICATIONS',
    subCategory: 'Final',
    unit: 'lot',
    materialRate: 650,
    labourRate: 0,
    labourHours: 0,
    totalRate: 650.00,
  },
];

// Helper function to get rate by code
export function getRateByCode(code: string): ConstructionRate | undefined {
  return AUSTRALIAN_CONSTRUCTION_RATES.find(r => r.code === code);
}

// Helper function to get rates by category
export function getRatesByCategory(category: SOWCategory): ConstructionRate[] {
  return AUSTRALIAN_CONSTRUCTION_RATES.filter(r => r.category === category);
}

// Helper to calculate typical house cost range
export function calculateTypicalHouseCost(floorAreaM2: number): { low: number; mid: number; high: number } {
  // Based on 2024 Australian averages
  // Budget: $1,800-2,200/m²
  // Mid-range: $2,200-3,000/m²
  // High-end: $3,000-4,500/m²
  return {
    low: Math.round(floorAreaM2 * 1900),
    mid: Math.round(floorAreaM2 * 2600),
    high: Math.round(floorAreaM2 * 3500),
  };
}

// Default overhead and margin percentages
export const DEFAULT_OVERHEADS = {
  siteOverheads: 8,      // Site supervision, temp facilities, etc.
  companyOverheads: 5,   // Insurance, admin, etc.
  contingency: 5,        // Unforeseen items
  margin: 10,            // Builder's margin
};
